export default function getSalesTaxRates() {
    // Sales tax rates for the 50 states
    const salesTaxRates = [
      { state: 'Alabama', rate: 0.04 },
      { state: 'Alaska', rate: 0 },
      { state: 'Arizona', rate: 0.056 },
      { state: 'Arkansas', rate: 0.065 },
      { state: 'California', rate: 0.0725 },
      { state: 'Colorado', rate: 0.029 },
      { state: 'Connecticut', rate: 0.0635 },
      { state: 'Delaware', rate: 0 },
      { state: 'Florida', rate: 0.06 },
      { state: 'Georgia', rate: 0.04 },
      { state: 'Hawaii', rate: 0.04 },
      { state: 'Idaho', rate: 0.06 },
      { state: 'Illinois', rate: 0.0625 },
      { state: 'Indiana', rate: 0.07 },
      { state: 'Iowa', rate: 0.06 },
      { state: 'Kansas', rate: 0.0615 },
      { state: 'Kentucky', rate: 0.06 },
      { state: 'Louisiana', rate: 0.05 },
      { state: 'Maine', rate: 0.055 },
      { state: 'Maryland', rate: 0.06 },
      { state: 'Massachusetts', rate: 0.0625 },
      { state: 'Michigan', rate: 0.06 },
        { state: 'Minnesota', rate: 0.07 },
        { state: 'Mississippi', rate: 0.07 },
        { state: 'Missouri', rate: 0.04225 },
        { state: 'Montana', rate: 0 },
        { state: 'Nebraska', rate: 0.055 },
        { state: 'Nevada', rate: 0.0685 },
        { state: 'New Hampshire', rate: 0 },
        { state: 'New Jersey', rate: 0.06625 },
        { state: 'New Mexico', rate: 0.05125 },
        { state: 'New York', rate: 0.04 },
        { state: 'North Carolina', rate: 0.0475 },
        { state: 'North Dakota', rate: 0.05 },
        { state: 'Ohio', rate: 0.0575 },
        { state: 'Oklahoma', rate: 0.045 },
        { state: 'Oregon', rate: 0 },
        { state: 'Pennsylvania', rate: 0.06 },
        { state: 'Rhode Island', rate: 0.07 },
        { state: 'South Carolina', rate: 0.06 },
        { state: 'South Dakota', rate: 0.04 },
        { state: 'Tennessee', rate: 0.07 },
        { state: 'Texas', rate: 0.0625 },
        { state: 'Utah', rate: 0.0595 },
        { state: 'Vermont', rate: 0.06 },
        { state: 'Virginia', rate: 0.053 },
        { state: 'Washington', rate: 0.065 },
        { state: 'West Virginia', rate: 0.06 },
        { state: 'Wisconsin', rate: 0.05 },
        { state: 'Wyoming', rate: 0.04 }
        ];

return salesTaxRates;
}
  